-- ┌─ SỔ SQL ──────────────────────────────────────────────────────────────────
-- │ KHÔNG THUỘC SỔ — tệp này không nâng cấp gì: đổ dữ liệu mồi cho danh mục nhịp.
-- │ Chạy lúc nào cũng được, chạy lại cũng được.
-- └───────────────────────────────────────────────────────────────────────────
-- ============================================================================
-- DỮ LIỆU MỒI: danh mục nhịp — 156 nhịp rút từ 2 tháng nhóm Lark Tỉnh thức
-- (nguồn: production/du-an/tinh-thuc-danh-sach-viec-lap-lai.md, 04/08/2026)
-- Chạy SAU schema.sql. Chạy lại nhiều lần không sao (on conflict do nothing).
-- ============================================================================
insert into danh_muc_nhip (ten, phong_ban, so_lan_da_lap) values
  ('Họp team kinh doanh', 'Marketing', 75),
  ('Học thầy Long', 'Bán hàng', 54),
  ('Check tiến độ khách hàng', 'Cung ứng', 54),
  ('Chữa bài tập cho khách', 'Cung ứng', 54),
  ('Nhắn tin hỏi thăm tình hình học tập, backtest phương pháp', 'Cung ứng', 54),
  ('Import data revshare', 'Tài chính', 51),
  ('check tn KH', 'Cung ứng', 50),
  ('Chăm sóc khách hàng coaching, chấm bài cho học viên coaching', 'Chuyên môn', 44),
  ('Học IPS', 'Cung ứng', 41),
  ('Follow up công nợ', 'Tài chính', 39),
  ('Follow up Affiliate Business', 'Tài chính', 38),
  ('Phân phối content', 'Marketing', 37),
  ('Chăm sóc khách hàng', 'Marketing', 32),
  ('Chia sẻ tín hiệu tham khảo', 'Chuyên môn', 29),
  ('Follow các dự án', 'Ban điều hành', 28),
  ('Giao ban kinh doanh', 'Marketing', 22),
  ('Quan sát và tổng hợp công việc', 'Vận hành', 19),
  ('Gọi tìm hiểu nhu cầu KH', 'Bán hàng', 18),
  ('Nuôi dưỡng KH tiềm năng', 'Bán hàng', 18),
  ('Review trải nghiệm khách hàng', 'Bán hàng', 18),
  ('Kick off tuần', 'Marketing', 17),
  ('Gọi điện tư vấn lead được phân bổ', 'Bán hàng', 16),
  ('Follow dự án Affiliate', 'Bán hàng', 15),
  ('Sắp xếp dự án', 'Vận hành', 14),
  ('Gọi lead RW35', 'Bán hàng', 13),
  ('Tài liệu lý quản lý công việc', 'Vận hành', 13),
  ('Tư vấn khách đã có lịch hẹn', 'Bán hàng', 12),
  ('Gọi KH RW35 và ZĐK', 'Bán hàng', 11),
  ('Hỗ trợ các KH đăng ký 3 hộp pro', 'Bán hàng', 11),
  ('Lọc tiếp tệp khách tiềm năng', 'Bán hàng', 11),
  ('Checkin cung ứng', 'Bán hàng', 11),
  ('Checkin kinh doanh', 'Bán hàng', 11),
  ('Tổng kết tuần', 'Marketing', 10),
  ('Rà soát lại các lead và gọi tư vấn KH', 'Bán hàng', 10),
  ('Lên kế hoạch tuần', 'Marketing', 9),
  ('Tham gia đào tạo nội bộ', 'Marketing', 9),
  ('Kế hoạch ứng dụng Integrity', 'Ban điều hành', 9),
  ('Kế hoạch dự án integrity', 'Vận hành', 9),
  ('sửa bài tập', 'Cung ứng', 9),
  ('Học SSS thầy Long', 'Cung ứng', 8),
  ('Nghiên cứu ngành', 'Marketing', 8),
  ('Check in giữa tuần', 'Marketing', 8),
  ('Rà soát lại list KH được phân bổ', 'Bán hàng', 8),
  ('Phát triển dự án Affiliate', 'Bán hàng', 8),
  ('Check in', 'Ban điều hành', 8),
  ('Quan sát cộng đồng', 'Chuyên môn', 8),
  ('Nghiên cứu thang giá trị giải pháp', 'Cung ứng', 7),
  ('Gọi tư vấn chốt sale KH', 'Bán hàng', 7),
  ('Gọi điện tiếp lead mới được chia', 'Bán hàng', 7),
  ('Học copywritting', 'Marketing', 7),
  ('Học email mkt', 'Marketing', 7),
  ('Hệ thống data', 'Vận hành', 7),
  ('Học bán hàng', 'Chuyên môn', 7),
  ('Checkin Trải nghiệm khách hàng', 'Cung ứng', 6),
  ('Lập kế hoạch tuần sau', 'Cung ứng', 6),
  ('Lên lịch hẹn tư vấn', 'Bán hàng', 6),
  ('Giữ nhịp vận hành', 'Ban điều hành', 6),
  ('họp team', 'Cung ứng', 6),
  ('lên ds KH', 'Cung ứng', 6),
  ('thúc đẩy học tập', 'Cung ứng', 6),
  ('Follow các khách PRO', 'Cung ứng', 5),
  ('Thiết kế phòng ban', 'Cung ứng', 5),
  ('Tiêu chí tốt nghiệp', 'Cung ứng', 5),
  ('Lên zoom giải đáp 1 số thắc mắc của KH', 'Bán hàng', 5),
  ('Nhắc lịch zđk', 'Marketing', 5),
  ('Nạp input Sale', 'Marketing', 5),
  ('Bộ phân loại KH', 'Vận hành', 5),
  ('Triển khai pháp lý ROVA', 'Bán hàng', 5),
  ('Chăm sóc khách coaching', 'Cung ứng', 5),
  ('Xây dựng giáo trình coaching', 'Chuyên môn', 5),
  ('Kiểm tra tổng thể các tính năng cỗ máy Trading', 'Cung ứng', 4),
  ('Nhóm cộng đồng PRO', 'Cung ứng', 4),
  ('Bán hàng', 'Marketing', 4),
  ('Check in online', 'Bán hàng', 4),
  ('Liên hệ KH mới PIC', 'Bán hàng', 4),
  ('Lọc lại KH cũ', 'Bán hàng', 4),
  ('Tham gia RW35', 'Bán hàng', 4),
  ('Cập nhật lại kiến thức bán hàng', 'Bán hàng', 4),
  ('Khai thác thông tin thị trường hàng hóa', 'Bán hàng', 4),
  ('Tư vấn khóa học', 'Bán hàng', 4),
  ('Xem gọi lại tệp tiềm năng', 'Bán hàng', 4),
  ('Cung ứng khách hàng webina 35', 'Cung ứng', 4),
  ('Tư vấn và hỗ trợ khách hàng', 'Marketing', 4),
  ('Họp coreteam', 'Vận hành', 4),
  ('Đưa task list coreteam lên click up', 'Vận hành', 4),
  ('Check in tuần', 'Tài chính', 4),
  ('Chốt lịch họp mr Vicky', 'Tài chính', 4),
  ('Các công việc Affiliate', 'Tài chính', 4),
  ('Brainstorm Dự án hệ thống kinh doanh 4.0', 'Bán hàng', 4),
  ('Lên chiến lược Nuôi dưỡng khách hàng và kế hoạch ZĐK', 'Bán hàng', 4),
  ('Lên kế hoạch triển khai doanh số Coaching', 'Bán hàng', 4),
  ('Sắp xếp mô hình kinh doanh phù hợp với pháp lý', 'Bán hàng', 4),
  ('Nhận định tt', 'Cung ứng', 4),
  ('chấm bài chị Phượng', 'Cung ứng', 4),
  ('lên kế hoạch tuần mới', 'Cung ứng', 4),
  ('Cập nhật tính năng Cỗ máy Trading', 'Cung ứng', 3),
  ('Học thêm về thị trường hàng hoá', 'Cung ứng', 3),
  ('Làm bài Form Tốt nghiệp: Trí tuệ+Thực chiến+Cảm nhận+Tâm thức', 'Cung ứng', 3),
  ('Quy trình học tập pro', 'Cung ứng', 3),
  ('Setup nhóm học tập theo level: Cấu trúc - Vai trò - Chức năng', 'Cung ứng', 3),
  ('Tính năng tracking tài khoản khách hàng', 'Cung ứng', 3),
  ('Tổng hợp kết quả giải đấu', 'Cung ứng', 3),
  ('Điều kiện đánh giá để khách hàng tốt nghiệp', 'Cung ứng', 3),
  ('Follow up quy trình RW35', 'Marketing', 3),
  ('Hoàn thiện salepage', 'Marketing', 3),
  ('Hoàn tất nghiên cứu thị trường', 'Marketing', 3),
  ('Thiết kế Salepage tư vấn', 'Marketing', 3),
  ('Triển khai kế hoạch xây dựng ROVA IPS', 'Marketing', 3),
  ('Lên mục tiêu tuần và tháng', 'Bán hàng', 3),
  ('Gọi chốt sale theo lịch hẹn', 'Bán hàng', 3),
  ('Gọi khách tham gia ZĐK nhưng chưa mua sản phẩm', 'Bán hàng', 3),
  ('Gọi lại danh sách khách hàng tiềm năng', 'Bán hàng', 3),
  ('Hỗ trợ chuyển rej ( 1 khách)', 'Bán hàng', 3),
  ('Hỗ trợ khách pro cũ', 'Bán hàng', 3),
  ('Lên danh sách hẹn gọi tệp đã lọc', 'Bán hàng', 3),
  ('Lên kịch bản chuyển ref', 'Bán hàng', 3),
  ('Lên mục tiêu tháng 6', 'Bán hàng', 3),
  ('Lên phương án hoàn thành mục tiêu sele', 'Bán hàng', 3),
  ('Thông tin lại khách chưa tham dự zoom', 'Bán hàng', 3),
  ('Bám sát mục tiêu kinh doanh', 'Ban điều hành', 3),
  ('Duy trì lịch giao ban', 'Ban điều hành', 3),
  ('Chia lead RW35', 'Marketing', 3),
  ('Lên content plan', 'Marketing', 3),
  ('Nghiên cứu khách hàng', 'Marketing', 3),
  ('Nghiên cứu ngành Trading', 'Marketing', 3),
  ('Nạp input content marketing, copywritting', 'Marketing', 3),
  ('Follow task list coreteam đầu ngày và cuối ngày', 'Vận hành', 3),
  ('Hệ thống cuộc họp cố định', 'Vận hành', 3),
  ('Kế hoạch tổng quan', 'Vận hành', 3),
  ('Nghiên cứu thị trường hàng hoá', 'Vận hành', 3),
  ('Nghiên cứu đưa integrity vào văn hoá', 'Vận hành', 3),
  ('OKRs dự án', 'Vận hành', 3),
  ('Tổng hợp tài liệu', 'Vận hành', 3),
  ('Đào tạo nội bộ', 'Vận hành', 3),
  ('Checkin RW35', 'Bán hàng', 3),
  ('Checkin khách hàng Coaching', 'Bán hàng', 3),
  ('Nghiên cứu thị trường hàng hoá phái sinh', 'Bán hàng', 3),
  ('Thiết kế thang giá trị sản phẩm', 'Bán hàng', 3),
  ('Thiết lập mục tiêu tháng 7', 'Bán hàng', 3),
  ('Tỉnh thức', 'Bán hàng', 3),
  ('Xây dựng mô hình kinh doanh', 'Bán hàng', 3),
  ('Cung ứng hỗ trợ khách mới - lam bài tập', 'Cung ứng', 3),
  ('hỗ trợ chị Giang', 'Cung ứng', 3),
  ('Chuẩn bị zoom định kỳ', 'Chuyên môn', 3)
on conflict (ten) do nothing;
